# Generated by Django 4.2 on 2023-05-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('intoroduction', models.CharField(max_length=50)),
                ('author_type', models.CharField(max_length=10)),
                ('book_name1', models.CharField(max_length=30)),
                ('book_content1', models.TextField()),
                ('book_name2', models.CharField(max_length=30)),
                ('book_content2', models.TextField()),
                ('book_name3', models.CharField(max_length=30)),
                ('book_content3', models.TextField()),
            ],
        ),
    ]
